{% set data= load_setup_py_data() %}
{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}
package:
  name: "ts-dsm"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_dsm = lsst.ts.dsm:run_dsm
    - shutdown_dsm = lsst.ts.dsm:shutdown_dsm

test:
  requires:
    - ts-conda-build =0.4
    - ts-salobj {{ salobj_version }}
    - ts-xml {{ xml_version }}
    - ts-utils
    - asyncinotify
  source_files:
    - bin
    - python
    - tests
    - pyproject.toml
  commands:
    - pytest -v

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-utils
    - asyncinotify

about:
  home: {{ project.get('urls')["repository"] }}
  license: {{ project.get('license')["text"] }}
  license_file: LICENSE
