{% set data= load_setup_py_data() %}
package:
  name: "ts-dsm"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_dsm = lsst.ts.dsm:run_dsm
    - shutdown_dsm = lsst.ts.dsm:shutdown_dsm

test:
  requires:
    - ts-conda-build =0.3
    - ts-salobj {{ salobj_version }}
    - ts-idl {{ idl_version }}
    - ts-utils
    - asyncinotify
    - pytz
  source_files:
    - bin
    - python
    - tests
    - pyproject.toml
  commands:
    - pytest -v

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-utils
    - asyncinotify
    - pytz

about:
  home: {{ data.get('project_urls')["Source Code"] }}
  license: {{ data.get('license') }}
  license_file: LICENSE
