{% set data= load_setup_py_data() %}
package:
  name: ts-dsm
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default')}}

source:
  path: ../

build:
  script: python -m pip install --ignore-installed .
  skip: True #[win]
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - TS_CONFIG_EAS_DIR

test:
  requires:
    - pytest
    - pytest-flake8
    - pytest-cov
    - asynctest
    - ts-dds
    - ts-salobj
    - ts-idl==v1.1.2_4.7.0
    - aionotify
    - pytz
  source_files:
    - bin
    - python
    - tests
    - setup.cfg
  commands:
    - pytest -v

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-dds
    - ts-salobj
    - aionotify
    - pytz

about:
  home: {{ data.get('project_urls')["Source Code"] }}
  license: {{ data.get('license') }}
  license_file: LICENSE
